#!/usr/bin/env node
/**
 * Embeds every built MCP App UI HTML file into a single JS module for Adobe I/O Runtime
 * deployment. Serverless actions only ship the webpack bundle - static/ is not deployed
 * alongside it - so each MCP App UI must ride inside the bundled index.js as a required JS
 * string instead of being read from disk at runtime.
 *
 * Discovers every actions/mcp-server/static/<name>.html built by scripts/build-ui.js and embeds
 * it under the camelCased key `<name>Html` (e.g. product-list.html -> productListHtml) -
 * matching the key each tool passes to loadUiHtml() in tools.js.
 */

const fs = require('fs')
const path = require('path')

const staticDir = path.join(__dirname, '../actions/mcp-server/static')
const outPath = path.join(__dirname, '../actions/mcp-server/embedded-ui.js')

if (!fs.existsSync(staticDir)) {
    console.error(`Missing ${staticDir}. Run "npm run build:ui" first.`)
    process.exit(1)
}

const toCamelCase = (stem) => stem.replace(/-([a-z0-9])/gi, (_, c) => c.toUpperCase())

const htmlFiles = fs.readdirSync(staticDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.html'))
    .map((entry) => entry.name)
    .sort()

if (htmlFiles.length === 0) {
    console.error(`No built MCP App UIs found in ${staticDir}. Run "npm run build:ui" first.`)
    process.exit(1)
}

const embedded = {}
for (const filename of htmlFiles) {
    const stem = filename.replace(/\.html$/, '')
    const key = `${toCamelCase(stem)}Html`
    embedded[key] = fs.readFileSync(path.join(staticDir, filename), 'utf8')
    console.log(`Embedded ${filename} as "${key}" (${(embedded[key].length / 1024).toFixed(1)} KB)`)
}

const output = `/*
 * Auto-generated by scripts/embed-ui.js — do not edit.
 * MCP App HTML inlined for Adobe I/O Runtime (serverless bundle has no static/ folder).
 */
module.exports = ${JSON.stringify(embedded, null, 2)}
`

fs.writeFileSync(outPath, output)
console.log(`Wrote ${outPath}`)
